model_params:
  name: 'BetaVAE'
  in_channels: 1
  latent_dim: 10
  loss_type: 'H'
  beta: 15.
  custom_architecture: False
  dcgan: False
  image_dim: 64

data_params:
  image_dir: "/content/drive/MyDrive/RtBB_experiment_code/Datasets/synthetic_simple_bw_filled"
  train_batch_size: 64
  val_batch_size:  64
  patch_size: 64
  num_workers: 2

exp_params:
  LR: 0.0025
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  gpus: [0]
  max_epochs: 150

logging_params:
  save_dir: "logs/"
  name: 'BetaVAE'