model_params:
  name: 'BetaTCVAE'
  in_channels: 3
  latent_dim: 10
  anneal_steps: 10000
  alpha: 1.
  beta:  6.
  gamma: 1.
  custom_architecture: True
  dcgan: False
  image_dim: 128

data_params:
  data_path: "/content/drive/MyDrive/Datasets/"
  dataset_name: "synthetic_gradient_shapes_128_simpler"
  train_batch_size: 64
  val_batch_size:  64
  patch_size: 128
  num_workers: 4

exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  gpus: [0]
  max_epochs: 100

logging_params:
  save_dir: "../VAE-logs/"
  name: 'BetaTCVAE'
